### ISSUE TITLE
What are the underlying principles mentioned in the article?

### ISSUE THREAD

**Issue by immadolf** [google/eng-practices#59]
> Aspects of software design are almost never a pure style issue or just a personal preference. They are based on **underlying principles** and should be weighed on those principles, not simply by personal opinion. Sometimes there are a few valid options. If the author can demonstrate (either through data or based on solid engineering principles) that several approaches are equally valid, then the reviewer should accept the preference of the author. Otherwise the choice is dictated by standard principles of software design.

**Comment by mkanat** [comment]
I've attempted to cover the most universal underlying principles in https://www.codesimplicity.com/book/. One can derive other principles from those, some of which would be specific to the technology being used.

**Comment by immadolf** [comment]
thank you ~
