### ISSUE TITLE
Site redirects to non-existent URL

### ISSUE THREAD

**Issue by uthbees** [google/eng-practices#61]
It's currently not possible to access the live version of this since [00a1e7c](https://github.com/google/eng-practices/commit/00a1e7cf60efb62ecbfe0ccb51fda8ff2646fedb), as the site now redirects to engineering.google, which is not connected to a web server.

Was it a mistake to add the CNAME file, or is it planned to put something up at engineering.google?

**Comment by adambender** [comment]
Access should be restored! Apologies for the confusion.
